### ISSUE TITLE
Incompatible with Nvidium

### ISSUE THREAD

**Issue by StuffOfSonny** [FiniteReality/embeddium#103]
Using Rubidium, I'm able to get Nvidium running (0.1.16-alpha as that version is compatible with Sodium 0.5.2), but not with any version of Embeddium. Nvidium doesn't even detect any version of Sodium at all with Embeddium, whereas it does with Rubidium.

**Comment by embeddedt** [comment]
Using Sodium addons with Embeddium is not officially supported (see the [compatibility page](https://github.com/embeddedt/embeddium/wiki/Compatibility#fabric-mods-sinytra-connector)).

If you choose to proceed with this, you will probably need to configure a [global mod alias](https://github.com/Sinytra/Connector#global-mod-aliases) in Connector so that it presents the `sodium` mod ID to Fabric mods. Rubidium chooses to do this by itself; I do not as Embeddium is not exactly the same as Sodium internally and it might cause subtle bugs.

**Comment by StuffOfSonny** [comment]
Disappointing, but understandable. Is Embeddium updated to Sodium 0.5.3, or will I have to keep using an outdated Nvidium once I set the Connector config?

**Comment by embeddedt** [comment]
Embeddium was updated to Sodium 0.5.3 a while ago.

**Comment by StuffOfSonny** [comment]
I apologize for taking your time away from whatever else you may be doing, but I'm still having trouble setting a global alias. I keep running into this error and do not know how to begin trying to hotfix it:
```[14:50:43] [INFO] [FabricLoader/Resolution]: Fix: add [], remove [], replace [[embeddium 0.2.5+mc1.20.1] -> add:sodium 0.5.3 ([[0.5.3,0.5.3]])]```

**Comment by embeddedt** [comment]
Maybe ask about it in the Connector server? https://discord.gg/mamk7z3TKZ

I haven't used global mod aliases myself, so I doubt I will be much help for it. :sweat_smile:
