### ISSUE TITLE
Embeddium color hue issue

### ISSUE THREAD

**Issue by LanceLuckiest** [FiniteReality/embeddium#172]
### Bug Description

Well basically this problem is that the color of some vanilla biomes is incorrect especially those of dark tone, this was tested with the following mods:

- Cavebiomeapi-1.16.5-1.4.2
- Caveandcliffs-1.16.5-7.2.0
- Embeddium-0.2.17+Mc1.16.5

Of course in Minecraft 1.16.5 using Forge 1.16.5 - 36.2.41 (All this including the mods with the default settings)

Here are some examples of the Biome Minecraft: Swamp being affected by this problem.

- This is when there is only the mod Embeddium-0.2.17+Mc1.16.5:

![2024-01-10_13 39 39](https://github.com/embeddedt/embeddium/assets/103775194/01d4e406-e64b-4264-940f-a88a8fb777e8)

- And here is when I add the mod Cavesandcliffs Backport and its dependence cavebiomeapi with Embeddium:

![2024-01-10_13 37 47](https://github.com/embeddedt/embeddium/assets/103775194/e7b3cb21-3a91-40df-bc72-24576f9833b4)

As you can see the color of the swamp is not correct, this also happens with some modified biomes mods like: oh the biomes you'll go.

### Reproduction Steps

Ok first install the mods:

-Cavebiomeapi-1.16.5-1.4.2
-Caveandcliffs-1.16.5-7.2.0
- Embeddium-0.2.17+Mc1.16.5

Then he adds them to his client, using Minecraft 1.16.5 with Forge 1.16.5 - 36.2.41. After loading the client, create a world in a normal way and look for biomes such as swamp, more than all biomes with dark tones. Upon finding it, you will see that such biome does not have the right colored hue.

### Log File

[latest.log](https://github.com/embeddedt/embeddium/files/13891946/latest.log)

**Comment by embeddedt** [comment]
This cannot be fixed by Embeddium; I looked into it before. Cave Biome API hacks into vanilla's biome system and forces biome retrieval to happen at a fixed Y coordinate. Since Embeddium takes a snapshot of a single 16x16x16 region of the world at a time, in most cases, this will result in biomes being retrieved outside that snapshot, which causes the default biome colors to be used.

You will need to remove Cave Biome API for biome coloring to work correctly.

**Comment by LanceLuckiest** [comment]
Just to be sure, there is no other solution besides just removing cave biomes api?

**Comment by Lymia** [comment]
I was dealing with this issue in my modpack as well. I went ahead and just made a version of CaveBiomeAPI that doesn't have this problem, since I have no hope that the original mod dev is even still around to fix it. Project seems long-abandoned.

https://github.com/Lymia/SimpleCaveBiomes
https://curseforge.com/minecraft/mc-mods/simplecavebiomes

Still under review on CurseForge, but, hopefully soon.
