### ISSUE TITLE
Just Stargate Mod dark world bug

### ISSUE THREAD

**Issue by xg787** [FiniteReality/embeddium#200]
### Bug Description

dark world
![2024-02-06_22 45 09](https://github.com/embeddedt/embeddium/assets/59268579/bd342344-e4fc-4e91-9821-ee974a831a4c)

### Reproduction Steps

create stargate
world goes dark

### Log File

no error in logs

**Comment by embeddedt** [comment]
The mod developer has been in contact on Discord about this, but I was unable to debug it further due to the mod causing excessive memory usage & system freezes when I attempted to run it on my machine. My suspicion is that they are loading too many textures and overwhelming the system's video memory, but I can't confirm this.

Also, another user said the mod works fine with Embeddium for them. :thinking:

Leaving this open for tracking purposes.

**Comment by xg787** [comment]
created a video showcasing the bug for more details
https://youtu.be/M1Y_tW7uwOk
(it happens around 1:30)

**Comment by onepieceluffyy** [comment]
Sometimes you can get this issue to trigger when reloading textures or switching resource packs

**Comment by Nolij** [comment]
> Sometimes you can get this issue to trigger when reloading textures or switching resource packs

This only happens with JSM installed though, right?

**Comment by onepieceluffyy** [comment]
> > Sometimes you can get this issue to trigger when reloading textures or switching resource packs
> 
> This only happens with JSM installed though, right?

Yes

**Comment by cyberdragon442** [comment]
> The mod developer has been in contact on Discord about this, but I was unable to debug it further due to the mod causing excessive memory usage & system freezes when I attempted to run it on my machine. My suspicion is that they are loading too many textures and overwhelming the system's video memory, but I can't confirm this.
> 
> Also, another user said the mod works fine with Embeddium for them. 🤔
> 
> Leaving this open for tracking purposes.

This appears to be the case. I can run other large texture mods like New Tardis Mod, Immersive Railroading, ex, with a ton of other mods, but JSG lags and crashes with less then 100 other mods. Unzipping the files it appear the are applying the textures as one whole thing instead of in pieces like most MC mods, aka more like a traditional large UV map. Some of their textures are 5MB or more, totaling over 100MB of textures, which is on par with those HD Immersive Railroading/Immersive Vehicles packs. Hopefully they can get the memory usage down to stop issues like this and make the mod a lot more playable.

**Comment by xg787** [comment]
fixed in jsg (hopefully)
https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/issues/10#issuecomment-2024134966
