### ISSUE TITLE
Pixies from Ice And Fire produce broken particles at certain angle and time

### ISSUE THREAD

**Issue by Matthysse** [FiniteReality/embeddium#232]
### Bug Description

Pixies from the Ice And Fire mod ([https://modrinth.com/mod/ice-and-fire-dragons](https://modrinth.com/mod/ice-and-fire-dragons)) produce broken particles at certain angle and time 

### Reproduction Steps

- Load game using Embeddium ((Neo)Forge), Ice And Fire
- Wait a bit and see the particles from the pixies going broken at certain angles:
![2024-03-14_18 00 20](https://github.com/embeddedt/embeddium/assets/32510957/fe91cfe3-01fb-4808-9dab-9d70393191b2)

It's hard to reproduce and sometimes does not want to appear...

### Log File

[latest.log](https://github.com/embeddedt/embeddium/files/14606518/latest.log)

**Comment by embeddedt** [comment]
I wasn't able to reproduce this issue after a few minutes of spawning pixies with just Ice & Fire and Embeddium installed. However, I have a theory as to why it happens. This explanation will be a bit technical, so you may wish to make an issue with Ice & Fire and point them to this message.

When rendering pixie dust, Ice & Fire's rendering code [changes the active texture and starts a buffer builder manually](https://github.com/AlexModGuy/Ice_and_Fire/blob/0b4cd08a71a185928ac21db3484b67d8886a382f/src/main/java/com/github/alexthe666/iceandfire/client/particle/ParticlePixieDust.java#L80-L89). This seems inconsistent with how other "custom" vanilla particles work, and seems potentially likely to cause the renderer to end up using the wrong texture or format when rendering particles later. I would suggest they change this code to use a similar strategy to vanilla's `MobAppearanceParticle`, which just uses the `MultiBufferSource` provided by vanilla with a custom render type, rather than controlling the renderer state themselves. 

I'm going to close this issue on my end as I'm not convinced it's an Embeddium bug, and I won't be able to fix it without a reliable way to reproduce it.
