### ISSUE TITLE
[1.19.2] Effective Cascades Not Working

### ISSUE THREAD

**Issue by SaltSouls** [FiniteReality/embeddium#24]
This was a bug back with Rubidium as well, but when using Embeddium, the cascade particles and sounds do not play.
Removing Embeddium seems to fix the issue.

**Comment by SiverDX** [comment]
There are already fixes for that https://github.com/bottomtextdanny/Effective-Forge-/pulls
But ports of that mod are no longer allowed, see description of https://www.curseforge.com/minecraft/mc-mods/effective

**Comment by embeddedt** [comment]
I can't easily fix this from my end, as that mod implements its effects using a [mixin into the vanilla renderer](https://github.com/bottomtextdanny/Effective-Forge-/blob/1.19.2/src/main/java/bottomtextdanny/effective_fg/mixin/LiquidBlockRendererMixin.java), which won't work with Embeddium, as it rewrites that code for improved speed. In theory I could add custom integration but that becomes very hard to maintain over time, especially since Embeddium supports many Minecraft versions. The best solution is for the other mod to merge those PRs and make an update.
