### ISSUE TITLE
Slow chunks

### ISSUE THREAD

**Issue by vlad0-0** [FiniteReality/embeddium#243]
### Request Description

Perhaps adding a feature that slows down the process of displaying new chunks would help reduce lags and latency in some cases. In case of a large number of mods, this feature may be useful to eliminate fps drops

**Comment by embeddedt** [comment]
You can already control how many CPU threads are used for chunk meshing calculations in Video Settings. The default is a fraction of your total CPU cores, clamped between a minimum of 1 and maximum of 10, so setting it to 1 guarantees only one thread will be used.

Otherwise, offering a finer-grained setting is not planned. In my testing, even in modpacks, the amount of CPU time used to mesh chunks is relatively minimal, and code from other mods/lag from the integrated server in singleplayer is a far bigger contributor to the problem.
