### ISSUE TITLE
Issue with alex's mobs lava vision potion

### ISSUE THREAD

**Issue by sherzzz10** [FiniteReality/embeddium#246]
### Bug Description

When using this mod alongside Alex's mobs, it seemingly disables or breaks the lava vision potions functionality

![2024-03-26_23 51 24](https://github.com/embeddedt/embeddium/assets/165118215/5e2b6b84-286f-4da2-b97c-29854b3c6ac6)

### Reproduction Steps

Use a lava vision potion with embeddium enabled 

### Log File

https://paste.atlauncher.com/view/8c65b5ac-0e51-4c77-9c7a-a93394711fda

**Comment by embeddedt** [comment]
This is caused by them replacing the vanilla fluid renderer hackily [here](https://github.com/AlexModGuy/AlexsMobs/blob/e1e9942a19e097b256da2d8da11b34ab1e904da1/src/main/java/com/github/alexthe666/alexsmobs/client/event/ClientEvents.java#L360-L371), which is bad practice as only one mod can do it at a time. (Also, it won't work with Embeddium.) Similarly to https://github.com/embeddedt/embeddium/issues/80, the best solution would be for them to contribute a proper API to Forge to allow customizing vanilla rendering in the way they need. This would be beneficial to many other mods, and Embeddium can support that properly.

**Comment by Jonathing** [comment]
Hello 👋 

I did some hackery on my own to solve this issue for a personal project. Along the way I found that ColorABGR.mult doesn't preserve the alpha of the color that's fed into it. This means that fluid types with `IClientFluidTypeExtensions` that supply their own alpha byte instead of relying on the transparency of the texture itself have the alpha part of their tint completely ignored. This happens in `FluidRenderer.calculateQuadColors`. I checked the workspace and saw that this issue was fixed in 1.20.1 but it's still present in 1.19.2. If you want to update that version of Embeddium any time soon, I'd recommend making a similar method (i.e. `ColorABGR.multPreserveAlpha`) as a stop-gap. If not, understandable. Cheers. 🥂
