### ISSUE TITLE
Alex's Cave issue rendering Peering Coprolith

### ISSUE THREAD

**Issue by LeKripiY** [FiniteReality/embeddium#268]
### Bug Description

With the Alex's Caves mod installed alongside embeddium, the block named Peering Coprolith doesn't render properly.
I already reported this issue to Alex's cave github a long time ago, but it resurfaced recently.
![image](https://github.com/embeddedt/embeddium/assets/77859121/8f657d0c-3ae2-41b2-877b-ca43efd8677b)
There is supposed to be glowing animated red eyes inside.
The issue over at Alex's cave's github was left marked as incompatibility, but I wonder if maybe you have an idea on this issue.

### Reproduction Steps

Have Both Alex's Caves and Embeddium mods installed, place Peering Coprolith, block parts render transparent.
Glitch exsist regarding both mods' versions (It was already there when Alex's Caves first released, and is still there with both mods up to date).

### Log File

[latest.log](https://github.com/embeddedt/embeddium/files/15053089/latest.log)

**Comment by embeddedt** [comment]
The issue is caused by Alex's Caves using multiple layered translucent faces for this block. With Embeddium installed, by default the faces are not sorted with respect to the camera position, which causes them to disappear sometimes. Enabling "Translucent Face Sorting" in Video Settings will fix it. We plan to eventually enable this by default in a future release once the performance regression of having it enabled is minimized.

However, the better solution would be for Alex's Caves to mark the block as not being translucent. From what I can tell, the outer shell is either fully transparent or fully opaque, so the cutout layer would work fine. Similarly, the inner shell seems to be opaque and doesn't let me see through to blocks on the other side. So I would say this is a bug on their end. Using the translucent render layer when it's not necessary will cause reduced performance with the vanilla renderer as well, not just Embeddium's.
