### ISSUE TITLE
Changelogs

### ISSUE THREAD

**Issue by ColonelGerdauf** [FiniteReality/embeddium#28]
It would be nice to provide some info in what changed in a given update. This will give some clarity with what has been fixed or added or removed in each update. Especially when people are expecting specific bug-fixes.

**Comment by embeddedt** [comment]
It's time-consuming to handwrite changelogs for four separate Minecraft versions. Generally I'd recommend using the [commits list](https://github.com/embeddedt/embeddium/commits/16.x/forge) by choosing the appropriate branch, and checking all commits made since the date of the previous release. However I may try to setup autogenerated changelogs as I did for ModernFix when I have time.

**Comment by embeddedt** [comment]
I came up with a compromise - write a shared changelog for all four versions and mention what version the changes applied to.

https://github.com/embeddedt/embeddium/wiki/Changelog
