### ISSUE TITLE
Snapshot update

### ISSUE THREAD

**Issue by ModxVoldHunter** [FiniteReality/embeddium#303]
### Request Description

24w18 to 24w21b (1.21)

**Comment by embeddedt** [comment]
This unfortunately won't happen in the near future, as I'm not able to continue maintaining the Fabric branch for 1.21 (see my [full writeup](https://hackmd.io/@embeddedt/r1jMxmUVR) for more context). While the mod is still being updated to snapshots on the NeoForge branch for development purposes, those aren't usable for playing the game since NeoForge doesn't exist for snapshots at the moment.

If and when NeoForge does release versions for snapshots, I'll be happy to publish these updates as I did during the 1.20.5 snapshot cycle.
