### ISSUE TITLE
Change Sodium stub version to 0.5.9+

### ISSUE THREAD

**Issue by Huaiker** [FiniteReality/embeddium#312]
### Request Description

When I was using Embeddium 0.3.20-1.20.6 and IRIS 1.7.1, it told me to replace Sodium0.5.9, which is currently 0.5.8

**Comment by xbxct** [comment]
Did it crash when you opened your inventory?

**Comment by xbxct** [comment]
The update needs to be delayed due to incompatibilities between the latest versions of mods.

**Comment by Huaiker** [comment]
> Did it crash when you opened your inventory?

I didn`t crash when I opened my inv

**Comment by embeddedt** [comment]
I looked into this briefly; at first glance I can fix this for 1.20.6. However, I can't do this on 1.20.1 because Sodium made breaking changes in 0.5.9, even though it was supposed to be a bugfix release.

If I make those changes in Embeddium, it will probably break some mods. Nonetheless, Iris depends on those changes. As such, Iris 1.7.0 will probably be the last version that works with Embeddium on 1.20.1, unless I find an alternative solution.

**Comment by xbxct** [comment]
If there are several mods, the developers themselves will add compatibility with embeddium.

**Comment by embeddedt** [comment]
I was not able to find any other mods that depend on the Sodium 0.5.8 version of that API, so I went ahead and prepared the change for the next release. Oculus seems to function still for the time being, but it may require an update in the future to continue working. Iris 1.7.2 works fine.

**Comment by embeddedt** [comment]
Embeddium 0.3.24 is compatible with the latest version of Iris and reports itself as Sodium 0.5.11.
