### ISSUE TITLE
Use No Error Context turns itself off upon restart

### ISSUE THREAD

**Issue by Barerock** [FiniteReality/embeddium#347]
### Bug Description

I currently have an incurable OpenGL spam problem caused by a known thang, but turning off error context doesn't work because it just turns itself back on.

### Reproduction Steps

Turn off, restart, it's on.

### Log File

https://mclo.gs/AuKiHjG

It's quite big.

**Comment by Barerock** [comment]
That was late. More details:
Forge 47.2.20
Embeddium 0.3.24
MC 1.20.1

The logs are being spammed by generic OpenGL error caused by flywheel iris compat when mechanical bearings in create are active. This is per world, not a constant. I want to turn the logs off because they seem to have no real import.

**Comment by Barerock** [comment]
For now, connector will run this mod https://modrinth.com/mod/suppressopengl1280

**Comment by embeddedt** [comment]
This issue should be reported to Flywheel/Iris compat. Disabling the no error context will not prevent the errors, and having it enabled is actually more likely to just cause a crash, because the driver is no longer required to even raise the error; it can just crash instead. OpenGL errors should be addressed at their root cause instead of just suppressing them.
