### ISSUE TITLE
Alex's Caves Depth Glass Visual Issue

### ISSUE THREAD

**Issue by mrdrewlego** [FiniteReality/embeddium#80]
**Mods with Compat Issue**
  Alex's Caves

**The Issue:**
  If using Alex's Caves v1.0.5 and embeddium v0.22, the depth glass in Alex's Caves will not function as intended.

**Steps to reproduce**
1. Load Alex's Caves and embeddium with their dependencies.
2. Access the blocks of glass from minecraft and depth glass from Alex's Caves.
3. Place the blocks underwater to see that the depth glass rendering is not working as intended.

**Additional context**
Without Embeddium: 
![2023-10-24_16 35 16](https://github.com/embeddedt/embeddium/assets/37915554/8a0c467c-0251-4269-b323-86d44e5a7d34)
With Embeddium:
![2023-10-24_16 36 30](https://github.com/embeddedt/embeddium/assets/37915554/013b0f0f-dc1f-404a-98aa-b40c19d26b08)

**Comment by embeddedt** [comment]
This is most likely caused by the mod modifying the vanilla fluid renderer with a mixin [here](https://github.com/AlexModGuy/AlexsCaves/blob/main/src/main/java/com/github/alexmodguy/alexscaves/mixin/client/LiquidBlockRendererMixin.java), which does not work with Embeddium as it replaces the fluid renderer with a faster alternative. I cannot fix it from my end alone without hardcoding special logic for that mod's block, which is not maintainable long-term. I would suggest reporting this to them.

**Comment by AlexModGuy** [comment]
creating a block tag to ignore fluid texture culling could be extremely useful beyond the scope of this issue. For example, if a mod adds some sort of "fake" water that they want to blend seamlessly with the real thing.

**Comment by embeddedt** [comment]
I agree, but it seems like something that should be added to Forge, not Embeddium. (Also I am not even sure if adding a tag is possible to do in a client-side mod.)
