### ISSUE TITLE
Translucent blocks do not correctly render elements inside them (affects slime block and honey block)

### ISSUE THREAD

**Issue by Kinsteen** [FiniteReality/embeddium#88]
In version 0.2.5 (maybe earlier versions, did not test), translucent blocks are not rendered properly, by default. If we enable the "Translucent Face Sorting", it shows normally.

For example, the slime block and the honey block both have a cuboid element inside them, which doesn't render most of the time with Embeddium. There is also a long standing [vanilla bug](https://bugs.mojang.com/browse/MC-163098), where some faces inside the cubes don't appear as well, but it's way more rare. It still happens even with "Translucent Face Sorting", it would be great if Embeddium could fix it as well :D

Also, I just saw in the screenshots, the textures seems more washed out?

## With Embeddium without "Translucent Face Sorting"
![2023-11-02_17 01 18](https://github.com/embeddedt/embeddium/assets/5410562/66009188-831b-48b4-bcfc-7f514bf9c5d9)
![2023-11-02_17 01 11](https://github.com/embeddedt/embeddium/assets/5410562/214dc86c-fdb3-4302-a0f8-f42dd04ff32d)
![2023-11-02_17 01 04](https://github.com/embeddedt/embeddium/assets/5410562/a01a2363-6e1a-42ec-a675-3c7781bf05d6)

## Without Embeddium / With Embeddium with "Translucent Face Sorting"
![2023-11-02_17 07 01](https://github.com/embeddedt/embeddium/assets/5410562/00a7e968-c03b-4c29-a2a8-a42db2b3b0da)
![2023-11-02_17 07 08](https://github.com/embeddedt/embeddium/assets/5410562/a369e90b-656b-4e83-ba4e-ca2db41334b8)
![2023-11-02_17 06 51](https://github.com/embeddedt/embeddium/assets/5410562/a381460b-8751-4af9-94b0-6570e5ba5f23)

Thanks!

**Comment by embeddedt** [comment]
The translucency sorting option exists specifically to fix this, but may have a minor performance impact so it's off by default. This is working as intended.

**Comment by Kinsteen** [comment]
I understand, but it's weird that by default, we have graphical glitches that are not there normally simply by installing Embeddium. I'm afraid that some mods who rely a lot on translucent blocks could have a lot of report because of this default option in Embeddium?

**Comment by embeddedt** [comment]
Translucency sorting has never existed in Sodium or Rubidium since their creation, so this wouldn't be a new issue.

Honestly, I would rather have it enabled by default myself, but the Sodium developers were not too keen on Embeddium having the feature while Sodium didn't, and also weren't interested in adding my implementation to Sodium, so this is my compromise. It is not hard to enable and modpacks can ship it enabled by default if they want.

**Comment by Kinsteen** [comment]
I just checked with Sodium, and I have the same glitches... It's weird that it's not something they want to fix, because it does degrade the experience somewhat.

About the vanilla bug I mentioned, you don't want to try to fix it as well, I'm guessing?

Thank you for the clarification!

**Comment by embeddedt** [comment]
They want to fix it, but only with an implementation they deem fast enough for their standards. Whereas I chose to write the simplest implementation that solved the problem, without impacting performance too much. Different philosophies :sweat_smile: 

Since the other bug happens in vanilla too, it's not required for Embeddium to fix, and I don't see an easy way of fixing it; it appears to be a side effect of how translucency sorting works.

**Comment by Kinsteen** [comment]
Yeah, I just saw their PR/issues about it. Thanks!
