### ISSUE TITLE
[1.20.1] Using Replay Mod through Sinytra Connector produces videos with GUI overlay.

### ISSUE THREAD

**Issue by VOLKOUL** [FiniteReality/embeddium#90]
This is not OBS, but a Replay Mod recording. I believe it is a bug, unless I overlooked something, as without Embeddium everything works as intended. Having it installed will result in videos with the Replay mod GUI overlay. (same thing with Rubidium)

https://github.com/embeddedt/embeddium/assets/97387920/19540da8-beac-4dad-afd2-ac0bc2cc94b7

**Comment by embeddedt** [comment]
There may be bugs & glitches that occur when using Embeddium alongside Fabric mods with advanced rendering (see https://github.com/embeddedt/embeddium/issues/43) as Embeddium is a fork of Sodium that is designed to work with Forge's rendering hooks and APIs, not Fabric's.

**Comment by VOLKOUL** [comment]
I see, thank you for the response. Btw, there is a new forge mod called Lazurite (an addition to Connector, as stated in their Discord and mod page) that has to do something with the Fabric Rendering API. I think you should take a look as it might offer a solution of some kind. Plus it has Embeddium as a dependency. You might already know about it, but here is the link anyways: https://www.curseforge.com/minecraft/mc-mods/lazurite

**Comment by embeddedt** [comment]
Lazurite will fix most common uses of Fabric Rendering API (e.g. machine models from Tech Reborn/Modern Industrialization) and I would definitely recommend using it alongside Embeddium for that purpose. 

However, for mods like Replay Mod, the issue frankly boils down to the fact that Fabric & Forge are not the same platform. Invasive/advanced mods are more likely to have issues when running on Connector than your average content mod, because they rely on specific nuances of vanilla that Forge probably doesn't replicate. I don't think Lazurite can work around these issues itself.

All that said, I will gladly accept a code contribution from someone, or some direction on what to change in Embeddium to fix the Replay Mod incompatibility, but I do not have the time to look into it for now.

I will add a paragraph explaining my stance with regards to Connector compatibility on the wiki, so that this is clear for future issue reports.
