### ISSUE TITLE
Seems to be incompatible with InspInspirations? Crashed when generating Nether portals.(1.18.2)

### ISSUE THREAD

**Issue by mosash41** [FiniteReality/embeddium#96]
First, sorry for my bad English.
I checked InspInspirations' GitHub first,and I found this → https://github.com/KnightMiner/Inspirations/issues/235
So I try to report the issue to you first.

[crash-2023-11-12_12.45.53-client.txt](https://github.com/embeddedt/embeddium/files/13327211/crash-2023-11-12_12.45.53-client.txt)

**Comment by embeddedt** [comment]
The issue is caused by Inspirations attempting to access blocks outside the 16x16x16 chunk being rendered. This is unsafe, but it uses a special hack in its code to make that work with vanilla. The hack does not apply to Embeddium, as it uses different rendering code.

I have applied a fix to prevent the game from crashing, but portal colors probably won't work correctly across chunk borders.
